import 'package:flutter/material.dart';

class DemoData {
  static const List<Map<String, String>> languages = [
    {'name': 'English', 'script': 'English', 'code': 'en'},
    {'name': 'Kannada', 'script': 'ಕನ್ನಡ', 'code': 'kn'},
    {'name': 'Hindi', 'script': 'हिंदी', 'code': 'hi'},
    {'name': 'Telugu', 'script': 'తెలుగు', 'code': 'te'},
    {'name': 'Malayalam', 'script': 'മലയാളം', 'code': 'ml'},
    {'name': 'Tamil', 'script': 'தமிழ்', 'code': 'ta'},
  ];

  static const List<Map<String, dynamic>> skills = [
    {'icon': Icons.restaurant, 'name': 'Cooking', 'kn': 'ಅಡುಗೆ'},
    {'icon': Icons.cleaning_services, 'name': 'Cleaning', 'kn': 'ಸ್ವಚ್ಛತೆ'},
    {'icon': Icons.local_shipping, 'name': 'Delivery', 'kn': 'ಡೆಲಿವರಿ'},
    {'icon': Icons.storefront, 'name': 'Shop Helper', 'kn': 'ಅಂಗಡಿ'},
    {'icon': Icons.construction, 'name': 'Labour', 'kn': 'ಕೂಲಿ'},
    {'icon': Icons.agriculture, 'name': 'Farming', 'kn': 'ಕೃಷಿ'},
    {'icon': Icons.child_care, 'name': 'Childcare', 'kn': 'ಮಕ್ಕಳ'},
    {'icon': Icons.elderly, 'name': 'Elder Care', 'kn': 'ವೃದ್ಧರು'},
    {'icon': Icons.build, 'name': 'Repair', 'kn': 'ದುರಸ್ತಿ'},
    {'icon': Icons.directions_car, 'name': 'Driving', 'kn': 'ಚಾಲನೆ'},
    {'icon': Icons.face_retouching_natural, 'name': 'Beauty', 'kn': 'ಸೌಂದರ್ಯ'},
    {'icon': Icons.inventory, 'name': 'Packing', 'kn': 'ಪ್ಯಾಕಿಂಗ್'},
    {'icon': Icons.security, 'name': 'Security', 'kn': 'ಭದ್ರತೆ'},
    {'icon': Icons.devices, 'name': 'Data Entry', 'kn': 'ಡೇಟಾ'},
    {'icon': Icons.format_paint, 'name': 'Painting', 'kn': 'ಬಣ್ಣ'},
    {'icon': Icons.checkroom, 'name': 'Tailoring', 'kn': 'ಹೊಲಿಗೆ'},
  ];

  static const List<Map<String, dynamic>> jobs = [
    {
      'icon': Icons.storefront,
      'title': 'Shop Assistant',
      'title_kn': 'ಅಂಗಡಿ ಸಹಾಯಕ',
      'company': 'Sri Ganesh Provision Store',
      'type': 'Shop Helper',
      'type_kn': 'ಅಂಗಡಿ',
      'location': 'Kodialbail',
      'location_kn': 'ಕೊಡಿಯಾಲ್‌ಬೈಲ್',
      'salary': '₹12,000',
      'period': '/mo',
      'period_kn': '/ತಿಂಗಳು',
      'distance': '6 min walk',
      'verified': true,
      'isUrgent': true,
    },
    {
      'icon': Icons.restaurant,
      'title': 'Kitchen Helper',
      'title_kn': 'ಅಡುಗೆ ಸಹಾಯಕ',
      'company': 'Hotel Udupi Delights',
      'type': 'Cooking',
      'type_kn': 'ಅಡುಗೆ',
      'location': 'Hampankatta',
      'location_kn': 'ಹಂಪನಕಟ್ಟೆ',
      'salary': '₹500',
      'period': '/day',
      'period_kn': '/ದಿನ',
      'distance': '12 min walk',
      'verified': true,
      'isUrgent': false,
    },
    {
      'icon': Icons.local_shipping,
      'title': 'Delivery Partner',
      'title_kn': 'ಡೆಲಿವರಿ ಪಾಲುದಾರ',
      'company': 'QuickMart Grocery',
      'type': 'Delivery',
      'type_kn': 'ಡೆಲಿವರಿ',
      'location': 'Kankanady',
      'location_kn': 'ಕಂಕನಾಡಿ',
      'salary': '₹600',
      'period': '/day',
      'period_kn': '/ದಿನ',
      'distance': '18 min walk',
      'verified': false,
      'isUrgent': true,
    },
    {
      'emoji': '🧹',
      'title': 'Cleaning Staff',
      'title_kn': 'ಶುಚಿಗೊಳಿಸುವ ಸಿಬ್ಬಂದಿ',
      'company': 'City Hospital',
      'type': 'Cleaning',
      'type_kn': 'ಸ್ವಚ್ಛತೆ',
      'location': 'Bejai',
      'location_kn': 'ಬಿಜೈ',
      'salary': '₹10,000',
      'period': '/mo',
      'period_kn': '/ತಿಂಗಳು',
      'distance': '15 min walk',
      'verified': true,
      'isUrgent': false,
    },
    {
      'emoji': '👷',
      'title': 'General Labour',
      'title_kn': 'ಸಾಮಾನ್ಯ ಕಾರ್ಮಿಕ',
      'company': 'BuildRight Construction',
      'type': 'Labour',
      'type_kn': 'ಕೂಲಿ',
      'location': 'Surathkal',
      'location_kn': 'ಸುರತ್ಕಲ್',
      'salary': '₹700',
      'period': '/day',
      'period_kn': '/ದಿನ',
      'distance': '25 min walk',
      'verified': false,
      'isUrgent': true,
    },
    {
      'emoji': '👵',
      'title': 'Elder Care Assistant',
      'title_kn': 'ವೃದ್ಧರ ಆರೈಕೆ ಸಹಾಯಕ',
      'company': 'HomeCare Services',
      'type': 'Elder Care',
      'type_kn': 'ವೃದ್ಧರು',
      'location': 'Kadri',
      'location_kn': 'ಕದ್ರಿ',
      'salary': '₹15,000',
      'period': '/mo',
      'period_kn': '/ತಿಂಗಳು',
      'distance': '10 min walk',
      'verified': true,
      'isUrgent': false,
    },
  ];

  static const List<Map<String, dynamic>> chatList = [
    {
      'initials': 'SG',
      'name': 'Sri Ganesh Store',
      'lastMessage': 'Can you come for a quick meeting tomorrow?',
      'time': '10:35 AM',
      'unread': 2,
      'jobTitle': 'Shop Assistant',
      'verified': true,
    },
    {
      'initials': 'HU',
      'name': 'Hotel Udupi',
      'lastMessage': 'We liked your profile. When can you start?',
      'time': '9:15 AM',
      'unread': 0,
      'jobTitle': 'Kitchen Helper',
      'verified': true,
    },
    {
      'initials': 'FM',
      'name': 'FreshMart',
      'lastMessage': 'Can you come for an interview tomorrow?',
      'time': 'Yesterday',
      'unread': 1,
      'jobTitle': 'Cashier',
      'verified': false,
    },
  ];

  static const List<Map<String, dynamic>> applicants = [
    {
      'name': 'Raju Kumar',
      'initial': 'R',
      'trustScore': 87,
      'skills': ['Shop Helper', 'Cleaning'],
      'distance': '6 min walk',
      'rating': 4.8,
      'jobsDone': 12,
      'showUp': '100%',
      'available': 'Immediately',
      'bestMatch': true,
      'status': 'New',
    },
    {
      'name': 'Suresh Mallya',
      'initial': 'S',
      'trustScore': 72,
      'skills': ['Delivery', 'Shop'],
      'distance': '18 min walk',
      'rating': 4.2,
      'jobsDone': 5,
      'showUp': '90%',
      'available': 'Tomorrow',
      'bestMatch': false,
      'status': 'Shortlisted',
    },
    {
      'name': 'Priya Devi',
      'initial': 'P',
      'trustScore': 65,
      'skills': ['Cook', 'Shop'],
      'distance': '8 min walk',
      'rating': 4.5,
      'jobsDone': 3,
      'showUp': '100%',
      'available': 'Immediately',
      'bestMatch': false,
      'status': 'Contacted',
    },
  ];

  static const List<Map<String, dynamic>> notifications = [
    {
      'type': 'urgent',
      'icon': Icons.warning_rounded,
      'title': 'URGENT JOB NEAR YOU!',
      'body': 'Sri Ganesh Store needs a Shop Helper within 500m — ₹500/day',
      'time': '5 min ago',
      'extra': '🚶 6 min walk',
      'group': 'Today',
    },
    {
      'type': 'offer',
      'icon': Icons.check_circle_outline,
      'title': 'Job Offer Received!',
      'body': 'Hotel Udupi Delights sent you an offer for Kitchen Helper',
      'time': '1 hour ago',
      'group': 'Today',
    },
    {
      'type': 'message',
      'icon': Icons.chat_bubble_outline,
      'title': 'New message from employer',
      'body': 'FreshMart: "Can you come for an interview tomorrow?"',
      'time': '3 hours ago',
      'group': 'Today',
    },
    {
      'type': 'trust',
      'icon': Icons.shield_outlined,
      'title': 'Trust Score increased!',
      'body': 'Your score went from 82 to 87. Get NGO verified to reach 95+',
      'time': 'Yesterday 2:30 PM',
      'group': 'Yesterday',
    },
    {
      'type': 'profile',
      'icon': Icons.account_circle_outlined,
      'title': 'Complete your profile',
      'body': 'Add a photo to get 3x more views',
      'time': 'Yesterday',
      'group': 'Yesterday',
    },
  ];
}
