class DemoData {
  static const List<Map<String, String>> languages = [
    {'name': 'English', 'script': 'English', 'code': 'en'},
    {'name': 'Kannada', 'script': 'ಕನ್ನಡ', 'code': 'kn'},
    {'name': 'Hindi', 'script': 'हिंदी', 'code': 'hi'},
    {'name': 'Telugu', 'script': 'తెలుగు', 'code': 'te'},
    {'name': 'Malayalam', 'script': 'മലയാളം', 'code': 'ml'},
    {'name': 'Tamil', 'script': 'தமிழ்', 'code': 'ta'},
  ];

  static const List<Map<String, String>> skills = [
    {'emoji': '🍳', 'name': 'Cooking', 'kn': 'ಅಡುಗೆ'},
    {'emoji': '🧹', 'name': 'Cleaning', 'kn': 'ಸ್ವಚ್ಛತೆ'},
    {'emoji': '🚚', 'name': 'Delivery', 'kn': 'ಡೆಲಿವರಿ'},
    {'emoji': '🏪', 'name': 'Shop Helper', 'kn': 'ಅಂಗಡಿ'},
    {'emoji': '👷', 'name': 'Labour', 'kn': 'ಕೂಲಿ'},
    {'emoji': '🌱', 'name': 'Farming', 'kn': 'ಕೃಷಿ'},
    {'emoji': '👶', 'name': 'Childcare', 'kn': 'ಮಕ್ಕಳ'},
    {'emoji': '👵', 'name': 'Elder Care', 'kn': 'ವೃದ್ಧರು'},
    {'emoji': '🔧', 'name': 'Repair', 'kn': 'ದುರಸ್ತಿ'},
    {'emoji': '🚗', 'name': 'Driving', 'kn': 'ಚಾಲನೆ'},
    {'emoji': '💇', 'name': 'Beauty', 'kn': 'ಸೌಂದರ್ಯ'},
    {'emoji': '📦', 'name': 'Packing', 'kn': 'ಪ್ಯಾಕಿಂಗ್'},
    {'emoji': '🛡️', 'name': 'Security', 'kn': 'ಭದ್ರತೆ'},
    {'emoji': '📱', 'name': 'Data Entry', 'kn': 'ಡೇಟಾ'},
    {'emoji': '🎨', 'name': 'Painting', 'kn': 'ಬಣ್ಣ'},
    {'emoji': '🧵', 'name': 'Tailoring', 'kn': 'ಹೊಲಿಗೆ'},
  ];

  static const List<Map<String, dynamic>> jobs = [
    {
      'emoji': '🏪',
      'title': 'Shop Assistant',
      'title_kn': 'ಅಂಗಡಿ ಸಹಾಯಕ',
      'company': 'Sri Ganesh Provision Store',
      'type': 'Full Time',
      'type_kn': 'ಪೂರ್ಣ ಸಮಯ',
      'location': 'Kodialbail',
      'location_kn': 'ಕೊಡಿಯಾಲ್‌ಬೈಲ್',
      'salary': '₹12,000',
      'period': '/mo',
      'period_kn': '/ತಿಂಗಳು',
      'distance': '6 min walk',
      'verified': true,
    },
    {
      'emoji': '🍳',
      'title': 'Kitchen Helper',
      'title_kn': 'ಅಡುಗೆ ಸಹಾಯಕ',
      'company': 'Hotel Udupi Delights',
      'type': 'Part Time',
      'type_kn': 'ಅರೆಕಾಲಿಕ',
      'location': 'Hampankatta',
      'location_kn': 'ಹಂಪನಕಟ್ಟೆ',
      'salary': '₹500',
      'period': '/day',
      'period_kn': '/ದಿನ',
      'distance': '12 min walk',
      'verified': true,
    },
    {
      'emoji': '🚚',
      'title': 'Delivery Partner',
      'title_kn': 'ಡೆಲಿವರಿ ಪಾಲುದಾರ',
      'company': 'QuickMart Grocery',
      'type': 'Flexible',
      'type_kn': 'ಹೊಂದಿಕೊಳ್ಳುವ',
      'location': 'Kankanady',
      'location_kn': 'ಕಂಕನಾಡಿ',
      'salary': '₹600',
      'period': '/day',
      'period_kn': '/ದಿನ',
      'distance': '18 min walk',
      'verified': false,
    },
  ];

  static const List<Map<String, dynamic>> chatList = [
    {
      'initials': 'SG',
      'name': 'Sri Ganesh Store',
      'lastMessage': 'Can you come for a quick meeting tomorrow?',
      'time': '10:35 AM',
      'unread': 2,
      'jobTitle': 'Shop Assistant',
      'verified': true,
    },
    {
      'initials': 'HU',
      'name': 'Hotel Udupi',
      'lastMessage': 'We liked your profile. When can you start?',
      'time': '9:15 AM',
      'unread': 0,
      'jobTitle': 'Kitchen Helper',
      'verified': true,
    },
    {
      'initials': 'FM',
      'name': 'FreshMart',
      'lastMessage': 'Can you come for an interview tomorrow?',
      'time': 'Yesterday',
      'unread': 1,
      'jobTitle': 'Cashier',
      'verified': false,
    },
  ];

  static const List<Map<String, dynamic>> applicants = [
    {
      'name': 'Raju Kumar',
      'initial': 'R',
      'trustScore': 87,
      'skills': ['Shop Helper', 'Cleaning'],
      'distance': '6 min walk',
      'rating': 4.8,
      'jobsDone': 12,
      'showUp': '100%',
      'available': 'Immediately',
      'bestMatch': true,
      'status': 'New',
    },
    {
      'name': 'Suresh Mallya',
      'initial': 'S',
      'trustScore': 72,
      'skills': ['Delivery', 'Shop'],
      'distance': '18 min walk',
      'rating': 4.2,
      'jobsDone': 5,
      'showUp': '90%',
      'available': 'Tomorrow',
      'bestMatch': false,
      'status': 'Shortlisted',
    },
    {
      'name': 'Priya Devi',
      'initial': 'P',
      'trustScore': 65,
      'skills': ['Cook', 'Shop'],
      'distance': '8 min walk',
      'rating': 4.5,
      'jobsDone': 3,
      'showUp': '100%',
      'available': 'Immediately',
      'bestMatch': false,
      'status': 'Contacted',
    },
  ];

  static const List<Map<String, dynamic>> notifications = [
    {
      'type': 'urgent',
      'icon': '🔴',
      'title': 'URGENT JOB NEAR YOU!',
      'body': 'Sri Ganesh Store needs a Shop Helper within 500m — ₹500/day',
      'time': '5 min ago',
      'extra': '🚶 6 min walk',
      'group': 'Today',
    },
    {
      'type': 'offer',
      'icon': '✅',
      'title': 'Job Offer Received! 🎉',
      'body': 'Hotel Udupi Delights sent you an offer for Kitchen Helper',
      'time': '1 hour ago',
      'group': 'Today',
    },
    {
      'type': 'message',
      'icon': '💬',
      'title': 'New message from employer',
      'body': 'FreshMart: "Can you come for an interview tomorrow?"',
      'time': '3 hours ago',
      'group': 'Today',
    },
    {
      'type': 'trust',
      'icon': '🛡️',
      'title': 'Trust Score increased!',
      'body': 'Your score went from 82 to 87. Get NGO verified to reach 95+',
      'time': 'Yesterday 2:30 PM',
      'group': 'Yesterday',
    },
    {
      'type': 'profile',
      'icon': '⏰',
      'title': 'Complete your profile',
      'body': 'Add a photo to get 3x more views',
      'time': 'Yesterday',
      'group': 'Yesterday',
    },
  ];
}
