class LocalizationService {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'choose_language': 'Choose your language',
      'continue': 'Continue',
      'step': 'Step',
      'of': 'of',
      'iam_a': 'I am a...',
      'worker': 'Worker',
      'worker_desc': 'I want to find jobs near me',
      'employer': 'Employer',
      'employer_desc': 'I want to hire workers',
      'enter_phone': 'Enter your phone',
      'phone_hint': '98765 43210',
      'otp_message': 'We will send an OTP to verify your number',
      'send_otp': 'Send OTP',
      'verify_otp': 'Verify OTP',
      'sent_to': 'Sent to',
      'didnt_receive': "Didn't receive?",
      'resend_otp': 'Resend OTP',
      'verify': 'Verify',
      'demo_hint': '💡 Enter any 4 digits for demo',
      'skills_title': 'What are your skills?',
      'skills_subtitle': 'Select 3 or more skills to get better matches',
      'continue_with_skills': 'Continue with {count} skills',
      'location_title': 'Where are you available?',
      'location_subtitle': 'Jobs will be shown within walking distance',
      'available_now': 'I am available to start now',
      'profile_setup_title': 'Set up your profile',
      'profile_setup_subtitle': 'This helps employers trust you more',
      'full_name': 'Full Name',
      'age': 'Age',
      'gender': 'Gender',
      'years_exp': 'Years of Experience',
      'complete_profile': 'Complete Profile',
      'skip_for_now': 'Skip for now',
      'all_jobs': 'All Jobs',
      'nearby': 'Nearby',
      'my_jobs': 'My Jobs',
      'earnings': 'Earnings',
      'profile': 'Profile',
      'search_jobs': 'Search jobs...',
      'min_walk': '{count} min walk',
      'verified': 'Verified',
      'apply_now': 'Apply Now',
      'quick_apply': 'Quick Apply',
      'applied': 'Applied',
      'earnings_wallet': 'Earnings Wallet',
      'total_balance': 'Total Balance',
      'weekly_earnings': 'Weekly Earnings',
      'recent_transactions': 'Recent Transactions',
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all as read',
      'trust_score': 'Trust Score',
      'ngo_verification': 'NGO Verification',
      'post_job': 'Post a Job',
      'view_applicants': 'View Applicants',
      'home': 'Home',
      'map': 'Map',
      'chat': 'Chat',
      'workers': 'Workers',
      'applicants': 'Applicants',
      'urgent_hiring': 'Urgent Hiring',
      'jobs_near_you': '{count} jobs near you need immediate joiners',
      'recommended': 'Recommended for you',
      'no_jobs_found': 'No jobs found',
      'try_different': 'Try a different category or search term',
      'hi': 'Hi',
      'jobs_done': 'Jobs Done',
      'earned': 'Earned',
      'show_up': 'Show-up',
      'member_since': 'Member since {date}',
      'my_skills': 'My Skills',
      'my_availability': 'My Availability',
      'work_history': 'Work History',
      'view_all_reviews': 'View all {count} reviews',
      'share': 'Share',
      'edit': 'Edit',
      'morning': 'Morning',
      'immediately': 'Immediately',
      'on_time': 'On Time',
      'honest': 'Honest',
      'hardworking': 'Hardworking',
      'reliable': 'Reliable',
      'would_rehire': 'Would Rehire',
      'pending': 'Pending',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'all_time': 'All Time',
      'withdraw': 'Withdraw to Bank',
      'available_balance': 'Available Balance',
      'total_earned_month': 'Total earned this month',
      'earnings_trend': 'Earnings Trend',
      'transactions': 'Transactions',
      'see_all': 'See All',
      'about_job': 'About this Job',
      'requirements': 'Requirements',
      'what_you_get': 'What you get',
      'openings': '{count} Openings',
      'rating': '{count} Rating',
      'hired': '{count} hired',
      'since': 'Since {year}',
      'enter_custom_skill': 'Enter your skill',
      'cancel': 'Cancel',
      'add': 'Add',
      'travel_distance_title': 'How far will you travel?',
      'days_available_title': 'When are you available?',
      'preferred_timing_title': 'Preferred timing',
      'available_right_now': 'Available Right Now?',
      'employers_see_ready': "Employers can see you're ready!",
      'continue_party': 'Continue 🎉',
      'change': 'Change',
      'walk': 'Walk',
      'nearby_dist': 'Nearby',
      'any_dist': 'Any',
      'afternoon': 'Afternoon',
      'evening': 'Evening',
      'any_time': 'Any Time',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
    },
    'kn': {
      'choose_language': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'continue': 'ಮುಂದುವರಿಯಿರಿ',
      'step': 'ಹಂತ',
      'of': 'ರಲ್ಲಿ',
      'iam_a': 'ನಾನು ಒಬ್ಬ...',
      'worker': 'ಕೆಲಸಗಾರ',
      'worker_desc': 'ನನ್ನ ಹತ್ತಿರ ಕೆಲಸ ಹುಡುಕಲು ಬಯಸುತ್ತೇನೆ',
      'employer': 'ಉದ್ಯೋಗದಾತ',
      'employer_desc': 'ನಾನು ಕೆಲಸಗಾರರನ್ನು ನೇಮಿಸಿಕೊಳ್ಳಲು ಬಯಸುತ್ತೇನೆ',
      'enter_phone': 'ನಿಮ್ಮ ಫೋನ್ ನಂಬರ್ ನಮೂದಿಸಿ',
      'phone_hint': '98765 43210',
      'otp_message': 'ನಿಮ್ಮ ಸಂಖ್ಯೆಯನ್ನು ಪರಿಶೀಲಿಸಲು ನಾವು OTP ಕಳುಹಿಸುತ್ತೇವೆ',
      'send_otp': 'OTP ಕಳುಹಿಸಿ',
      'verify_otp': 'OTP ಪರಿಶೀಲಿಸಿ',
      'sent_to': 'ಕಳುಹಿಸಲಾಗಿದೆ',
      'didnt_receive': 'ಸ್ವೀಕರಿಸಿಲ್ಲವೇ?',
      'resend_otp': 'OTP ಮರುಕಳುಹಿಸಿ',
      'verify': 'ಪರಿಶೀಲಿಸಿ',
      'demo_hint': '💡 ಡೆಮೊಗಾಗಿ ಯಾವುದೇ 4 ಅಂಕೆಗಳನ್ನು ನಮೂದಿಸಿ',
      'skills_title': 'ನಿಮ್ಮ ಕೌಶಲ್ಯಗಳು ಯಾವುವು?',
      'skills_subtitle': 'ಉತ್ತಮ ಹೊಂದಾಣಿಕೆಗಳನ್ನು ಪಡೆಯಲು 3 ಅಥವಾ ಹೆಚ್ಚಿನ ಕೌಶಲ್ಯಗಳನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'continue_with_skills': '{count} ಕೌಶಲ್ಯಗಳೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
      'location_title': 'ನೀವು ಎಲ್ಲಿ ಲಭ್ಯರಿದ್ದೀರಿ?',
      'location_subtitle': 'ನಡೆಯುವ ದೂರದಲ್ಲಿರುವ ಕೆಲಸಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತದೆ',
      'available_now': 'ನಾನು ಈಗಲೇ ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧನಿದ್ದೇನೆ',
      'profile_setup_title': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಿ',
      'profile_setup_subtitle': 'ಇದು ಉದ್ಯೋಗದಾತರು ನಿಮ್ಮನ್ನು ಹೆಚ್ಚು ನಂಬಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ',
      'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
      'age': 'ವಯಸ್ಸು',
      'gender': 'ಲಿಂಗ',
      'years_exp': 'ಅನುಭವದ ವರ್ಷಗಳು',
      'complete_profile': 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ',
      'skip_for_now': 'ಸದ್ಯಕ್ಕೆ ಬಿಟ್ಟುಬಿಡಿ',
      'all_jobs': 'ಎಲ್ಲಾ ಕೆಲಸಗಳು',
      'nearby': 'ಹತ್ತಿರದ',
      'my_jobs': 'ನನ್ನ ಕೆಲಸಗಳು',
      'earnings': 'ಗಳಿಕೆ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'search_jobs': 'ಕೆಲಸ ಹುಡುಕಿ...',
      'min_walk': '{count} ನಿಮಿಷದ ನಡಿಗೆ',
      'verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      'apply_now': 'ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
      'quick_apply': 'ತ್ವರಿತ ಅರ್ಜಿ',
      'applied': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
      'earnings_wallet': 'ಗಳಿಕೆಯ ವಾಲೆಟ್',
      'total_balance': 'ಒಟ್ಟು ಬ್ಯಾಲೆನ್ಸ್',
      'weekly_earnings': 'ವಾರದ ಗಳಿಕೆ',
      'recent_transactions': 'ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'mark_all_read': 'ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ',
      'trust_score': 'ನಂಬಿಕೆಯ ಸ್ಕೋರ್',
      'ngo_verification': 'NGO ಪರಿಶೀಲನೆ',
      'post_job': 'ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ',
      'view_applicants': 'ಅರ್ಜಿದಾರರನ್ನು ವೀಕ್ಷಿಸಿ',
      'home': 'ಮುಖಪುಟ',
      'map': 'ನಕ್ಷೆ',
      'chat': 'ಚಾಟ್',
      'workers': 'ಕೆಲಸಗಾರರು',
      'applicants': 'ಅರ್ಜಿದಾರರು',
      'urgent_hiring': 'ತುರ್ತು ನೇಮಕಾತಿ',
      'jobs_near_you': 'ನಿಮ್ಮ ಹತ್ತಿರದ {count} ಕೆಲಸಗಳಿಗೆ ತಕ್ಷಣದ ಕೆಲಸಗಾರರು ಬೇಕಾಗಿದ್ದಾರೆ',
      'recommended': 'ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾದ ಕೆಲಸಗಳು',
      'no_jobs_found': 'ಯಾವುದೇ ಕೆಲಸಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      'try_different': 'ಬೇರೆ ವರ್ಗ ಅಥವಾ ಹುಡುಕಾಟ ಪದವನ್ನು ಬಳಸಿ ನೋಡಿ',
      'hi': 'ನಮಸ್ಕಾರ',
      'jobs_done': 'ಪೂರ್ಣಗೊಳಿಸಿದ ಕೆಲಸಗಳು',
      'earned': 'ಗಳಿಕೆ',
      'show_up': 'ಹಾಜರಾತಿ',
      'member_since': '{date} ರಿಂದ ಸದಸ್ಯರು',
      'my_skills': 'ನನ್ನ ಕೌಶಲ್ಯಗಳು',
      'my_availability': 'ನನ್ನ ಲಭ್ಯತೆ',
      'work_history': 'ಕೆಲಸದ ಇತಿಹಾಸ',
      'view_all_reviews': 'ಎಲ್ಲಾ {count} ವಿಮರ್ಶೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      'share': 'ಹಂಚಿಕೊಳ್ಳಿ',
      'edit': 'ತಿದ್ದಿ',
      'morning': 'ಬೆಳಿಗ್ಗೆ',
      'immediately': 'ತಕ್ಷಣ',
      'on_time': 'ಸರಿಯಾದ ಸಮಯ',
      'honest': 'ಪ್ರಾಮಾಣಿಕ',
      'hardworking': 'ಕಷ್ಟಪಟ್ಟು ಕೆಲಸ ಮಾಡುವವರು',
      'reliable': 'ನಂಬಿಕಸ್ಥ',
      'would_rehire': 'ಮತ್ತೆ ನೇಮಿಸಿಕೊಳ್ಳುವರು',
      'pending': 'ಬಾಕಿ ಇದೆ',
      'this_week': 'ಈ ವಾರ',
      'this_month': 'ಈ ತಿಂಗಳು',
      'all_time': 'ಎಲ್ಲಾ ಸಮಯದ',
      'withdraw': 'ಬ್ಯಾಂಕಿಗೆ ವರ್ಗಾಯಿಸಿ',
      'available_balance': 'ಲಭ್ಯವಿರುವ ಹಣ',
      'total_earned_month': 'ಈ ತಿಂಗಳ ಒಟ್ಟು ಗಳಿಕೆ',
      'earnings_trend': 'ಗಳಿಕೆಯ ಪ್ರವೃತ್ತಿ',
      'transactions': 'ವಹಿವಾಟುಗಳು',
      'see_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'about_job': 'ಈ ಕೆಲಸದ ಬಗ್ಗೆ',
      'requirements': 'ಅಗತ್ಯತೆಗಳು',
      'what_you_get': 'ನಿಮಗೆ ಏನು ಸಿಗುತ್ತದೆ',
      'openings': '{count} ಉದ್ಯೋಗಾವಕಾಶಗಳು',
      'rating': '{count} ರೇಟಿಂಗ್',
      'hired': '{count} ನೇಮಕಗೊಂಡವರು',
      'since': '{year} ರಿಂದ',
      'enter_custom_skill': 'ನಿಮ್ಮ ಕೌಶಲ್ಯವನ್ನು ನಮೂದಿಸಿ',
      'cancel': 'ರದ್ದು',
      'add': 'ಸೇರಿಸಿ',
      'travel_distance_title': 'ಎಷ್ಟು ದೂರ ಹೋಗಬಲ್ಲಿರಿ?',
      'days_available_title': 'ಯಾವಾಗ ಲಭ್ಯರಿದ್ದೀರಿ?',
      'preferred_timing_title': 'ಆದ್ಯತೆಯ ಸಮಯ',
      'available_right_now': 'ಈಗ ಕೆಲಸಕ್ಕೆ ತಯಾರಿದ್ದೀರಾ?',
      'employers_see_ready': 'ಉದ್ಯೋಗದಾತರು ನೀವು ಸಿದ್ಧರಿದ್ದೀರಿ ಎಂದು ನೋಡಬಹುದು!',
      'continue_party': 'ಮುಂದುವರಿಯಿರಿ 🎉',
      'change': 'ಬದಲಾಯಿಸಿ',
      'walk': 'ನಡಿಗೆ',
      'nearby_dist': 'ಹತ್ತಿರದ',
      'any_dist': 'ಯಾವುದೇ',
      'afternoon': 'ಮಧ್ಯಾಹ್ನ',
      'evening': 'ಸಂಜೆ',
      'any_time': 'ಯಾವುದೇ ಸಮಯ',
      'mon': 'ಸೋಮ',
      'tue': 'ಮಂಗಳ',
      'wed': 'ಬುಧ',
      'thu': 'ಗುರು',
      'fri': 'ಶುಕ್ರ',
      'sat': 'ಶನಿ',
      'sun': 'ಭಾನು',
    },
  };

  static String translate(String key, String lang, {Map<String, String>? args}) {
    String text = _translations[lang]?[key] ?? _translations['en']?[key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }
    return text;
  }
}
