class LocalizationService {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'choose_language': 'Choose your language',
      'choose_language_subtitle': 'Select your preferred language',
      'welcome': 'Welcome to EmployMe',
      'welcome_desc': 'Find nearby work or hire trusted local staff',
      'looking_for_work': 'Looking for Work',
      'looking_for_work_desc': 'No resume needed • Local jobs',
      'im_hiring': "I'm Hiring",
      'im_hiring_desc': 'Post jobs • Find workers',
      'already_have_account': 'Already have an account? ',
      'sign_in': 'Sign In',
      'terms_privacy': 'By continuing you agree to our Terms & Privacy Policy',
      'continue': 'Continue',
      'step': 'Step',
      'of': 'of',
      'iam_a': 'I am a...',
      'worker': 'Worker',
      'worker_desc': 'I want to find jobs near me',
      'employer': 'Employer',
      'employer_desc': 'I want to hire workers',
      'enter_phone': 'Enter your phone',
      'phone_hint': '98765 43210',
      'otp_message': 'We will send an OTP to verify your number',
      'send_otp': 'Send OTP',
      'verify_otp': 'Verify OTP',
      'sent_to': 'Sent to',
      'didnt_receive': "Didn't receive?",
      'resend_otp': 'Resend OTP',
      'verify': 'Verify',
      'demo_hint': '💡 Enter any 4 digits for demo',
      'skills_title': 'What can you do?',
      'skills_subtitle': 'Tap all that apply — no degree needed!',
      'skills_selected': '{count} skills selected',
      'max_skills': 'Max 5 skills',
      'continue_with_skills': 'Continue with {count} skills',
      'location_title': 'Where are you available?',
      'location_subtitle': 'Jobs will be shown within walking distance',
      'available_now': 'I am available to start now',
      'profile_setup_title': 'Set up your profile',
      'profile_setup_subtitle': 'This helps employers trust you more',
      'full_name': 'Full Name',
      'age': 'Age',
      'gender': 'Gender',
      'years_exp': 'Years of Experience',
      'complete_profile': 'Complete Profile',
      'skip_for_now': 'Skip for now',
      'all_jobs': 'All Jobs',
      'nearby': 'Nearby',
      'my_jobs': 'My Jobs',
      'earnings': 'Earnings',
      'profile': 'Profile',
      'search_jobs': 'Search jobs...',
      'min_walk': '{count} min walk',
      'verified': 'Verified',
      'apply_now': 'Apply Now',
      'quick_apply': 'Quick Apply',
      'applied': 'Applied',
      'earnings_wallet': 'Earnings Wallet',
      'total_balance': 'Total Balance',
      'weekly_earnings': 'Weekly Earnings',
      'recent_transactions': 'Recent Transactions',
      'notifications': 'Notifications',
      'mark_all_read': 'Mark all as read',
      'trust_score': 'Trust Score',
      'ngo_verification': 'NGO Verification',
      'post_job': 'Post a Job',
      'view_applicants': 'View Applicants',
      'home': 'Home',
      'map': 'Map',
      'chat': 'Chat',
      'workers': 'Workers',
      'applicants': 'Applicants',
      'urgent_hiring': 'Urgent Hiring',
      'jobs_near_you': '{count} jobs near you need immediate joiners',
      'recommended': 'Recommended for you',
      'no_jobs_found': 'No jobs found',
      'try_different': 'Try a different category or search term',
      'hi': 'Hi',
      'jobs_done': 'Jobs Done',
      'earned': 'Earned',
      'show_up': 'Show-up',
      'member_since': 'Member since {date}',
      'my_skills': 'My Skills',
      'my_availability': 'My Availability',
      'work_history': 'Work History',
      'view_all_reviews': 'View all {count} reviews',
      'share': 'Share',
      'edit': 'Edit',
      'morning': 'Morning',
      'immediately': 'Immediately',
      'on_time': 'On Time',
      'honest': 'Honest',
      'hardworking': 'Hardworking',
      'reliable': 'Reliable',
      'would_rehire': 'Would Rehire',
      'pending': 'Pending',
      'this_week': 'This Week',
      'this_month': 'This Month',
      'all_time': 'All Time',
      'withdraw': 'Withdraw to Bank',
      'available_balance': 'Available Balance',
      'total_earned_month': 'Total earned this month',
      'earnings_trend': 'Earnings Trend',
      'transactions': 'Transactions',
      'see_all': 'See All',
      'about_job': 'About this Job',
      'requirements': 'Requirements',
      'what_you_get': 'What you get',
      'openings': '{count} Openings',
      'rating': '{count} Rating',
      'hired': '{count} hired',
      'since': 'Since {year}',
      'enter_custom_skill': 'Enter your skill',
      'cancel': 'Cancel',
      'add': 'Add',
      'travel_distance_title': 'How far will you travel?',
      'days_available_title': 'When are you available?',
      'preferred_timing_title': 'Preferred timing',
      'available_right_now': 'Available Right Now?',
      'employers_see_ready': "Employers can see you're ready!",
      'cant_find_skill': "Can't find your skill? Add it +",
      'Cooking': 'Cooking',
      'Cleaning': 'Cleaning',
      'Delivery': 'Delivery',
      'Shop Helper': 'Shop Helper',
      'Labour': 'Labour',
      'Farming': 'Farming',
      'Childcare': 'Childcare',
      'Elder Care': 'Elder Care',
      'Repair': 'Repair',
      'Driving': 'Driving',
      'Beauty': 'Beauty',
      'Packing': 'Packing',
      'Security': 'Security',
      'Data Entry': 'Data Entry',
      'Painting': 'Painting',
      'Tailoring': 'Tailoring',
      'Other': 'Other',
      'continue_party': 'Continue 🎉',
      'change': 'Change',
      'walk': 'Walk',
      'nearby_dist': 'Nearby',
      'any_dist': 'Any',
      'afternoon': 'Afternoon',
      'evening': 'Evening',
      'midnight': 'Midnight',
      'any_time': 'Any Time',
      'mon': 'Mon',
      'tue': 'Tue',
      'wed': 'Wed',
      'thu': 'Thu',
      'fri': 'Fri',
      'sat': 'Sat',
      'sun': 'Sun',
      'more_coming_soon': 'More languages coming soon',
      'good_morning': 'Good morning',
      'active_postings': 'Active Postings',
      'view_all': 'View All ({count})',
      'post_new_job': 'Post New Job',
      'applicants_label': 'Applicants',
      'reviews': 'Reviews',
      'analytics': 'Analytics',
      'verified_business': 'Verified Business',
      'find_workers_now': 'Urgent Hiring',
      'post_in_seconds': 'find available candidate now',
      'free': 'FREE',
      'expires_in': 'Expires in {days}',
      'high_interest': 'High Interest',
      'active': 'Active',
      'boost': 'Boost',
      'recent_applicants': 'Recent Applicants',
      'view': 'View',
      'days': 'days',
      'messages': 'Messages',
      'unread': 'unread',
      'search_conversations': 'Search conversations...',
      'search_jobs_title': 'Search Jobs',
      'distance_from_you': 'Distance from you',
      'job_type_label': 'Job Type',
      'pay_range': 'Pay Range',
      'full_time': 'Full Time',
      'part_time': 'Part Time',
      'daily_wage': 'Daily Wage',
      'weekend_only': 'Weekend Only',
      'per_day': 'per Day',
      'per_month': 'per Month',
      'per_hour': 'per Hour',
      'recent_searches': 'Recent searches',
      'match_availability': 'Match my availability',
      'show_jobs_on': 'Only show jobs on: Mon-Fri',
      'reset_filters': 'Reset Filters',
      'show_n_jobs': 'Show {count} Jobs',
      'what_job_looking': 'What job are you looking for?',
      'submit_application': 'Submit Application',
      'confirm_details': 'Confirm Details',
      'share_with_employer': "We'll share these with the employer",
      'application_sent': 'Application Sent! 🎉',
      'contact_soon': '{company} will contact you soon',
      'usually_within': 'Usually within 2 hours',
      'view_application': 'View Application',
      'find_more_jobs': 'Find More Jobs',
      'share_friend': 'Share with a friend who needs work →',
      'applying_for': 'Applying for...',
      'step_of': 'Step {current} of {total}',
      'when_start': 'When can you start?',
      'today': 'Today',
      'tomorrow': 'Tomorrow',
      'discuss': 'Discuss',
      'add_message': 'Add a message (optional)',
      'msg_placeholder': 'Hi, I am interested in this position. I have experience in shop work...',
      'total_earned': 'Total Earned',
      'jobs_done_label': 'Jobs Done',
      'get_verified': 'Get Verified',
      'request_verification': 'Request Verification',
      'become_ngo_verified': 'Become NGO Verified',
      'ngo_3x_text': 'Workers with NGO verification get 3x more job offers',
      'three_simple_steps': '3 Simple Steps',
      'submit_details_step': 'Submit your details',
      'submit_details_desc': 'We share your info securely with a trusted NGO near you',
      'ngo_contacts_step': 'NGO contacts you',
      'ngo_contacts_desc': 'An NGO volunteer calls you within 2 working days',
      'quick_meet_step': 'Quick in-person meet',
      'quick_meet_desc': 'Brief 10-min meeting at a nearby community center',
      'free_takes_days': '100% Free • Takes 2-3 days',
      'aadhaar_text': 'Your Aadhaar is never stored by EmployMe',
      'verified_ngo_partners': 'Verified NGO Partners Near You',
      'select_this_ngo': 'Select This NGO',
      'agree_verification': 'I agree to an in-person verification meeting with the selected NGO',
      'sms_works_everyone': 'Works for everyone',
      'apply_no_resume': 'Apply without a resume',
      'dual_verification': 'Dual-layer verification',
      'dont_leave_behind': "We don't leave anyone behind",
      'different_title': 'What Makes Us Different',
      'gps_title': 'Hyperlocal GPS Matching',
      'active_posts_count': '{count} Active Posts',
      'hired_count': '{count} Hired',
      'all_jobs_cat': 'All Jobs',
      'cooking_cat': 'Cooking',
      'delivery_cat': 'Delivery',
      'cleaning_cat': 'Cleaning',
      'shop_cat': 'Shop',
      'labour_cat': 'Labour',
      'repair_cat': 'Repair',
      'no_skills_added': 'No skills added yet',
      'shop_assistant': 'Shop Assistant',
      'delivery_partner': 'Delivery Partner',
      'immediate_start': 'Immediate Start',
      'no_degree': 'No degree or certificate required',
      'basic_comm': 'Basic Kannada or Hindi communication',
      'honest_punctual': 'Honest, punctual, hardworking',
      'lifting': 'Can lift boxes (up to 10kg)',
      'free_lunch': 'Free Lunch',
      'weekly_pay': 'Weekly Pay',
      'hike': 'Salary Hike',
      'bonus': 'Bonus',
      'what_is_this': 'What is this?',
      'community_verified': 'Community Verified',
      'good': 'Good',
      'business_name': 'Sri Ganesh Provision Store',
      'kitchen_helper': 'Kitchen Helper',
      'shop_clean': 'Shop • Clean',
      'cook_shop': 'Cook • Shop',
      'march': 'March',
      'aug': 'Aug',
      'jul': 'Jul',
    },
    'kn': {
      'choose_language': 'ನಿಮ್ಮ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'choose_language_subtitle': 'ನಿಮ್ಮ ಆದ್ಯತೆಯ ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ',
      'welcome': 'EmployMe ಗೆ ಸ್ವಾಗತ',
      'welcome_desc': 'ಹತ್ತಿರದ ಕೆಲಸವನ್ನು ಹುಡುಕಿ ಅಥವಾ ವಿಶ್ವಾಸಾರ್ಹ ಸ್ಥಳೀಯ ಸಿಬ್ಬಂದಿಯನ್ನು ನೇಮಿಸಿ',
      'looking_for_work': 'ಕೆಲಸ ಹುಡುಕುತ್ತಿದ್ದೇನೆ',
      'looking_for_work_desc': 'ರೆಸ್ಯೂಮ್ ಅಗತ್ಯವಿಲ್ಲ • ಸ್ಥಳೀಯ ಕೆಲಸಗಳು',
      'im_hiring': 'ನೇಮಕಾತಿ ಮಾಡುತ್ತಿದ್ದೇನೆ',
      'im_hiring_desc': 'ಕೆಲಸಗಳನ್ನು ಪೋಸ್ಟ್ ಮಾಡಿ • ಕೆಲಸಗಾರರನ್ನು ಹುಡುಕಿ',
      'already_have_account': 'ಈಗಾಗಲೇ ಖಾತೆ ಹೊಂದಿದ್ದೀರಾ? ',
      'sign_in': 'ಸೈನ್ ಇನ್',
      'terms_privacy': 'ಮುಂದುವರಿಯುವ ಮೂಲಕ ನೀವು ನಮ್ಮ ನಿಯಮಗಳು ಮತ್ತು ಗೌಪ್ಯತೆ ನೀತಿಯನ್ನು ಒಪ್ಪುತ್ತೀರಿ',
      'continue': 'ಮುಂದುವರಿಯಿರಿ',
      'step': 'ಹಂತ',
      'of': 'ರಲ್ಲಿ',
      'iam_a': 'ನಾನು ಒಬ್ಬ...',
      'worker': 'ಕೆಲಸಗಾರ',
      'worker_desc': 'ನನ್ನ ಹತ್ತಿರ ಕೆಲಸ ಹುಡುಕಲು ಬಯಸುತ್ತೇನೆ',
      'employer': 'ಉದ್ಯೋಗದಾತ',
      'employer_desc': 'ನಾನು ಕೆಲಸಗಾರರನ್ನು ನೇಮಿಸಿಕೊಳ್ಳಲು ಬಯಸುತ್ತೇನೆ',
      'enter_phone': 'ನಿಮ್ಮ ಫೋನ್ ನಂಬರ್ ನಮೂದಿಸಿ',
      'phone_hint': '98765 43210',
      'otp_message': 'ನಿಮ್ಮ ಸಂಖ್ಯೆಯನ್ನು ಪರಿಶೀಲಿಸಲು ನಾವು OTP ಕಳುಹಿಸುತ್ತೇವೆ',
      'send_otp': 'OTP ಕಳುಹಿಸಿ',
      'verify_otp': 'OTP ಪರಿಶೀಲಿಸಿ',
      'sent_to': 'ಕಳುಹಿಸಲಾಗಿದೆ',
      'didnt_receive': 'ಸ್ವೀಕರಿಸಿಲ್ಲವೇ?',
      'resend_otp': 'OTP ಮರುಕಳುಹಿಸಿ',
      'verify': 'ಪರಿಶೀಲಿಸಿ',
      'demo_hint': '💡 ಡೆಮೊಗಾಗಿ ಯಾವುದೇ 4 ಅಂಕೆಗಳನ್ನು ನಮೂದಿಸಿ',
      'skills_title': 'ನೀವು ಏನು ಮಾಡಬಲ್ಲಿರಿ?',
      'skills_subtitle': 'ಡಿಗ್ರಿ ಬೇಡ, ನಿಮ್ಮ ಕೌಶಲ್ಯ ಸಾಕು!',
      'skills_selected': '{count} ಕೌಶಲ್ಯಗಳನ್ನು ಆಯ್ಕೆ ಮಾಡಲಾಗಿದೆ',
      'max_skills': 'ಗರಿಷ್ಠ 5 ಕೌಶಲ್ಯಗಳು',
      'continue_with_skills': '{count} ಕೌಶಲ್ಯಗಳೊಂದಿಗೆ ಮುಂದುವರಿಯಿರಿ',
      'location_title': 'ನೀವು ಎಲ್ಲಿ ಲಭ್ಯರಿದ್ದೀರಿ?',
      'location_subtitle': 'ನಡೆಯುವ ದೂರದಲ್ಲಿರುವ ಕೆಲಸಗಳನ್ನು ತೋರಿಸಲಾಗುತ್ತದೆ',
      'available_now': 'ನಾನು ಈಗಲೇ ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧನಿದ್ದೇನೆ',
      'profile_setup_title': 'ನಿಮ್ಮ ಪ್ರೊಫೈಲ್ ಹೊಂದಿಸಿ',
      'profile_setup_subtitle': 'ಇದು ಉದ್ಯೋಗದಾತರು ನಿಮ್ಮನ್ನು ಹೆಚ್ಚು ನಂಬಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ',
      'full_name': 'ಪೂರ್ಣ ಹೆಸರು',
      'age': 'ವಯಸ್ಸು',
      'gender': 'ಲಿಂಗ',
      'years_exp': 'ಅನುಭವದ ವರ್ಷಗಳು',
      'complete_profile': 'ಪ್ರೊಫೈಲ್ ಪೂರ್ಣಗೊಳಿಸಿ',
      'skip_for_now': 'ಸದ್ಯಕ್ಕೆ ಬಿಟ್ಟುಬಿಡಿ',
      'all_jobs': 'ಎಲ್ಲಾ ಕೆಲಸಗಳು',
      'nearby': 'ಹತ್ತಿರದ',
      'my_jobs': 'ನನ್ನ ಕೆಲಸಗಳು',
      'earnings': 'ಗಳಿಕೆ',
      'profile': 'ಪ್ರೊಫೈಲ್',
      'search_jobs': 'ಕೆಲಸ ಹುಡುಕಿ...',
      'min_walk': '{count} ನಿಮಿಷದ ನಡಿಗೆ',
      'verified': 'ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      'apply_now': 'ಈಗಲೇ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
      'quick_apply': 'ತ್ವರಿತ ಅರ್ಜಿ',
      'applied': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಲಾಗಿದೆ',
      'earnings_wallet': 'ಗಳಿಕೆಯ ವಾಲೆಟ್',
      'total_balance': 'ಒಟ್ಟು ಬ್ಯಾಲೆನ್ಸ್',
      'weekly_earnings': 'ವಾರದ ಗಳಿಕೆ',
      'recent_transactions': 'ಇತ್ತೀಚಿನ ವಹಿವಾಟುಗಳು',
      'notifications': 'ಅಧಿಸೂಚನೆಗಳು',
      'mark_all_read': 'ಎಲ್ಲವನ್ನೂ ಓದಿದಂತೆ ಗುರುತಿಸಿ',
      'trust_score': 'ನಂಬಿಕೆಯ ಸ್ಕೋರ್',
      'ngo_verification': 'NGO ಪರಿಶೀಲನೆ',
      'post_job': 'ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ',
      'view_applicants': 'ಅರ್ಜಿದಾರರನ್ನು ವೀಕ್ಷಿಸಿ',
      'home': 'ಮುಖಪುಟ',
      'map': 'ನಕ್ಷೆ',
      'chat': 'ಚಾಟ್',
      'workers': 'ಕೆಲಸಗಾರರು',
      'applicants': 'ಅರ್ಜಿದಾರರು',
      'urgent_hiring': 'ತುರ್ತು ನೇಮಕಾತಿ',
      'jobs_near_you': 'ನಿಮ್ಮ ಹತ್ತಿರದ {count} ಕೆಲಸಗಳಿಗೆ ತಕ್ಷಣದ ಕೆಲಸಗಾರರು ಬೇಕಾಗಿದ್ದಾರೆ',
      'recommended': 'ನಿಮಗಾಗಿ ಶಿಫಾರಸು ಮಾಡಲಾದ ಕೆಲಸಗಳು',
      'no_jobs_found': 'ಯಾವುದೇ ಕೆಲಸಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      'try_different': 'ಬೇರೆ ವರ್ಗ ಅಥವಾ ಹುಡುಕಾಟ ಪದವನ್ನು ಬಳಸಿ ನೋಡಿ',
      'hi': 'ನಮಸ್ಕಾರ',
      'jobs_done': 'ಪೂರ್ಣಗೊಳಿಸಿದ ಕೆಲಸಗಳು',
      'earned': 'ಗಳಿಕೆ',
      'show_up': 'ಹಾಜರಾತಿ',
      'member_since': '{date} ರಿಂದ ಸದಸ್ಯರು',
      'my_skills': 'ನನ್ನ ಕೌಶಲ್ಯಗಳು',
      'my_availability': 'ನನ್ನ ಲಭ್ಯತೆ',
      'work_history': 'ಕೆಲಸದ ಇತಿಹಾಸ',
      'view_all_reviews': 'ಎಲ್ಲಾ {count} ವಿಮರ್ಶೆಗಳನ್ನು ವೀಕ್ಷಿಸಿ',
      'share': 'ಹಂಚಿಕೊಳ್ಳಿ',
      'edit': 'ತಿದ್ದಿ',
      'morning': 'ಬೆಳಿಗ್ಗೆ',
      'immediately': 'ತಕ್ಷಣ',
      'on_time': 'ಸರಿಯಾದ ಸಮಯ',
      'honest': 'ಪ್ರಾಮಾಣಿಕ',
      'hardworking': 'ಕಷ್ಟಪಟ್ಟು ಕೆಲಸ ಮಾಡುವವರು',
      'reliable': 'ನಂಬಿಕಸ್ಥ',
      'would_rehire': 'ಮತ್ತೆ ನೇಮಿಸಿಕೊಳ್ಳುವರು',
      'pending': 'ಬಾಕಿ ಇದೆ',
      'this_week': 'ಈ ವಾರ',
      'this_month': 'ಈ ತಿಂಗಳು',
      'all_time': 'ಎಲ್ಲಾ ಸಮಯದ',
      'withdraw': 'ಬ್ಯಾಂಕಿಗೆ ವರ್ಗಾಯಿಸಿ',
      'available_balance': 'ಲಭ್ಯವಿರುವ ಹಣ',
      'total_earned_month': 'ಈ ತಿಂಗಳ ಒಟ್ಟು ಗಳಿಕೆ',
      'earnings_trend': 'ಗಳಿಕೆಯ ಪ್ರವೃತ್ತಿ',
      'transactions': 'ವಹಿವಾಟುಗಳು',
      'see_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
      'about_job': 'ಈ ಕೆಲಸದ ಬಗ್ಗೆ',
      'requirements': 'ಅಗತ್ಯತೆಗಳು',
      'what_you_get': 'ನಿಮಗೆ ಏನು ಸಿಗುತ್ತದೆ',
      'openings': '{count} ಉದ್ಯೋಗಾವಕಾಶಗಳು',
      'rating': '{count} ರೇಟಿಂಗ್',
      'hired': '{count} ನೇಮಕಗೊಂಡವರು',
      'since': '{year} ರಿಂದ',
      'enter_custom_skill': 'ನಿಮ್ಮ ಕೌಶಲ್ಯವನ್ನು ನಮೂದಿಸಿ',
      'cancel': 'ರದ್ದು',
      'add': 'ಸೇರಿಸಿ',
      'travel_distance_title': 'ಎಷ್ಟು ದೂರ ಹೋಗಬಲ್ಲಿರಿ?',
      'days_available_title': 'ಯಾವಾಗ ಲಭ್ಯರಿದ್ದೀರಿ?',
      'preferred_timing_title': 'ಆದ್ಯತೆಯ ಸಮಯ',
      'available_right_now': 'ಈಗ ಕೆಲಸಕ್ಕೆ ತಯಾರಿದ್ದೀರಾ?',
      'employers_see_ready': 'ಉದ್ಯೋಗದಾತರು ನೀವು ಸಿದ್ಧರಿದ್ದೀರಿ ಎಂದು ನೋಡಬಹುದು!',
      'cant_find_skill': 'ನಿಮ್ಮ ಕೌಶಲ್ಯ ಸಿಗುತ್ತಿಲ್ಲವೇ? ಅದನ್ನು ಸೇರಿಸಿ +',
      'Cooking': 'ಅಡುಗೆ',
      'Cleaning': 'ಸ್ವಚ್ಛತೆ',
      'Delivery': 'ಡೆಲಿವರಿ',
      'Shop Helper': 'ಅಂಗಡಿ',
      'Labour': 'ಕೂಲಿ',
      'Farming': 'ಕೃಷಿ',
      'Childcare': 'ಮಕ್ಕಳ',
      'Elder Care': 'ವೃದ್ಧರು',
      'Repair': 'ದುರಸ್ತಿ',
      'Driving': 'ಚಾಲನೆ',
      'Beauty': 'ಸೌಂದರ್ಯ',
      'Packing': 'ಪ್ಯಾಕಿಂಗ್',
      'Security': 'ಭದ್ರತೆ',
      'Data Entry': 'ಡೇಟಾ',
      'Painting': 'ಬಣ್ಣ',
      'Tailoring': 'ಹೊಲಿಗೆ',
      'Other': 'ಇತರೆ',
      'continue_party': 'ಮುಂದುವರಿಯಿರಿ 🎉',
      'change': 'ಬದಲಾಯಿಸಿ',
      'walk': 'ನಡಿಗೆ',
      'nearby_dist': 'ಹತ್ತಿರದ',
      'any_dist': 'ಯಾವುದೇ',
      'afternoon': 'ಮಧ್ಯಾಹ್ನ',
      'evening': 'ಸಂಜೆ',
      'midnight': 'ಮಧ್ಯರಾತ್ರಿ',
      'any_time': 'ಯಾವುದೇ ಸಮಯ',
      'mon': 'ಸೋಮ',
      'tue': 'ಮಂಗಳ',
      'wed': 'ಬುಧ',
      'thu': 'ಗುರು',
      'fri': 'ಶುಕ್ರ',
      'sat': 'ಶನಿ',
      'sun': 'ಭಾನು',
      'more_coming_soon': 'ಇನ್ನಷ್ಟು ಭಾಷೆಗಳು ಶೀಘ್ರದಲ್ಲೇ ಬರಲಿವೆ',
      'good_morning': 'ಶುಭೋದಯ',
      'active_postings': 'ಸಕ್ರಿಯ ಪೋಸ್ಟಿಂಗ್‌ಗಳು',
      'view_all': 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ ({count})',
      'post_new_job': 'ಹೊಸ ಕೆಲಸ ಪೋಸ್ಟ್ ಮಾಡಿ',
      'applicants_label': 'ಅರ್ಜಿದಾರರು',
      'reviews': 'ವಿಮರ್ಶೆಗಳು',
      'analytics': 'ವಿಶ್ಲೇಷಣೆ',
      'verified_business': 'ಪರಿಶೀಲಿಸಿದ ವ್ಯಾಪಾರ',
      'find_workers_now': 'ತುರ್ತು ನೇಮಕಾತಿ',
      'post_in_seconds': 'ಲಭ್ಯವಿರುವ ಅಭ್ಯರ್ಥಿಗಳನ್ನು ಈಗಲೇ ಹುಡುಕಿ',
      'free': 'ಉಚಿತ',
      'expires_in': '{days} ದಿನಗಳಲ್ಲಿ ಮುಕ್ತಾಯವಾಗುತ್ತದೆ',
      'high_interest': 'ಹೆಚ್ಚಿನ ಆಸಕ್ತಿ',
      'active': 'ಸಕ್ರಿಯ',
      'boost': 'ಬೂಸ್ಟ್',
      'recent_applicants': 'ಇತ್ತೀಚಿನ ಅರ್ಜಿದಾರರು',
      'view': 'ವೀಕ್ಷಿಸಿ',
      'days': 'ದಿನಗಳು',
      'messages': 'ಸಂದೇಶಗಳು',
      'unread': 'ಓದದ',
      'search_conversations': 'ಸಂಭಾಷಣೆಗಳನ್ನು ಹುಡುಕಿ...',
      'search_jobs_title': 'ಕೆಲಸ ಹುಡುಕಿ',
      'distance_from_you': 'ನಿಮ್ಮಿಂದ ದೂರ',
      'job_type_label': 'ಕೆಲಸದ ಪ್ರಕಾರ',
      'pay_range': 'ಸಂಬಳ',
      'full_time': 'ಪೂರ್ಣ ಸಮಯ',
      'part_time': 'ಅರೆಕಾಲಿಕ',
      'daily_wage': 'ದೈನಿಕ ಕೂಲಿ',
      'weekend_only': 'ವಾರಾಂತ್ಯ ಮಾತ್ರ',
      'per_day': 'ಪ್ರತಿ ದಿನ',
      'per_month': 'ಪ್ರತಿ ತಿಂಗಳು',
      'per_hour': 'ಪ್ರತಿ ಗಂಟೆ',
      'recent_searches': 'ಇತ್ತೀಚಿನ ಹುಡುಕಾಟಗಳು',
      'match_availability': 'ನನ್ನ ಲಭ್ಯತೆ ಹೊಂದಿಸಿ',
      'show_jobs_on': 'ಸೋಮ-ಶುಕ್ರ ಕೆಲಸಗಳನ್ನು ಮಾತ್ರ ತೋರಿಸಿ',
      'reset_filters': 'ಫಿಲ್ಟರ್‌ಗಳನ್ನು ರೀಸೆಟ್ ಮಾಡಿ',
      'show_n_jobs': '{count} ಕೆಲಸಗಳನ್ನು ತೋರಿಸಿ',
      'what_job_looking': 'ನೀವು ಯಾವ ಕೆಲಸ ಹುಡುಕುತ್ತಿದ್ದೀರಿ?',
      'submit_application': 'ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
      'confirm_details': 'ವಿವರಗಳನ್ನು ಖಚಿತಪಡಿಸಿ',
      'share_with_employer': 'ನಾವು ಇವುಗಳನ್ನು ಉದ್ಯೋಗದಾತರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳುತ್ತೇವೆ',
      'application_sent': 'ಅರ್ಜಿ ಕಳುಹಿಸಲಾಗಿದೆ! 🎉',
      'contact_soon': '{company} ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತಾರೆ',
      'usually_within': 'ಸಾಮಾನ್ಯವಾಗಿ 2 ಗಂಟೆಗಳಲ್ಲಿ',
      'view_application': 'ಅರ್ಜಿ ವೀಕ್ಷಿಸಿ',
      'find_more_jobs': 'ಇನ್ನಷ್ಟು ಕೆಲಸ ಹುಡುಕಿ',
      'share_friend': 'ಕೆಲಸ ಬೇಕಾದ ಸ್ನೇಹಿತರೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ →',
      'applying_for': 'ಅರ್ಜಿ ಸಲ್ಲಿಸುತ್ತಿದ್ದೇನೆ...',
      'step_of': 'ಹಂತ {current} / {total}',
      'when_start': 'ನೀವು ಯಾವಾಗ ಪ್ರಾರಂಭಿಸಬಹುದು?',
      'today': 'ಇಂದು',
      'tomorrow': 'ನಾಳೆ',
      'discuss': 'ಚರ್ಚಿಸಿ',
      'add_message': 'ಸಂದೇಶ ಸೇರಿಸಿ (ಐಚ್ಛಿಕ)',
      'msg_placeholder': 'ನಮಸ್ಕಾರ, ಈ ಹುದ್ದೆಯಲ್ಲಿ ನನಗೆ ಆಸಕ್ತಿ ಇದೆ. ಅಂಗಡಿ ಕೆಲಸದಲ್ಲಿ ನನಗೆ ಅನುಭವ ಇದೆ...',
      'total_earned': 'ಒಟ್ಟು ಗಳಿಕೆ',
      'jobs_done_label': 'ಮಾಡಿದ ಕೆಲಸಗಳು',
      'get_verified': 'ಪರಿಶೀಲನೆ ಪಡೆಯಿರಿ',
      'request_verification': 'ಪರಿಶೀಲನೆ ಕೋರಿ',
      'become_ngo_verified': 'NGO ಪರಿಶೀಲಿಸಿ ಆಗಿ',
      'ngo_3x_text': 'NGO ಪರಿಶೀಲನೆ ಇರುವ ಕೆಲಸಗಾರರು 3 ಪಟ್ಟು ಹೆಚ್ಚು ಕೆಲಸ ಕೊಡುಗೆ ಪಡೆಯುತ್ತಾರೆ',
      'three_simple_steps': '3 ಸರಳ ಹಂತಗಳು',
      'submit_details_step': 'ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಸಲ್ಲಿಸಿ',
      'submit_details_desc': 'ನಾವು ನಿಮ್ಮ ಮಾಹಿತಿಯನ್ನು ನಿಮ್ಮ ಹತ್ತಿರದ NGO ಗೆ ಸುರಕ್ಷಿತವಾಗಿ ಹಂಚಿಕೊಳ್ಳುತ್ತೇವೆ',
      'ngo_contacts_step': 'NGO ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತದೆ',
      'ngo_contacts_desc': 'NGO ಸ್ವಯಂಸೇವಕರು 2 ಕೆಲಸದ ದಿನಗಳಲ್ಲಿ ನಿಮಗೆ ಕರೆ ಮಾಡುತ್ತಾರೆ',
      'quick_meet_step': 'ತ್ವರಿತ ಭೇಟಿ',
      'quick_meet_desc': 'ಹತ್ತಿರದ ಸಮುದಾಯ ಕೇಂದ್ರದಲ್ಲಿ 10 ನಿಮಿಷದ ಭೇಟಿ',
      'free_takes_days': '100% ಉಚಿತ • 2-3 ದಿನಗಳು ತೆಗೆದುಕೊಳ್ಳುತ್ತದೆ',
      'aadhaar_text': 'ನಿಮ್ಮ ಆಧಾರ್ EmployMe ನಲ್ಲಿ ಎಂದಿಗೂ ಸಂಗ್ರಹಿಸಲ್ಪಡುವುದಿಲ್ಲ',
      'verified_ngo_partners': 'ನಿಮ್ಮ ಹತ್ತಿರದ ಪರಿಶೀಲಿಸಿದ NGO ಪಾಲುದಾರರು',
      'select_this_ngo': 'ಈ NGO ಆಯ್ಕೆಮಾಡಿ',
      'agree_verification': 'ಆಯ್ಕೆ ಮಾಡಿದ NGO ಜೊತೆ ಭೇಟಿಗೆ ಒಪ್ಪುತ್ತೇನೆ',
      'sms_works_everyone': 'ಎಲ್ಲರಿಗೂ ಕೆಲಸ ಮಾಡುತ್ತದೆ',
      'apply_no_resume': 'ರೆಸ್ಯೂಮೆ ಇಲ್ಲದೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ',
      'dual_verification': 'ದ್ವಿ-ಸ್ತರ ಪರಿಶೀಲನೆ',
      'dont_leave_behind': 'ನಾವು ಯಾರನ್ನೂ ಹಿಂದೆ ಬಿಡುವುದಿಲ್ಲ',
      'different_title': 'ನಮ್ಮನ್ನು ಭಿನ್ನವಾಗಿಸುವುದು ಏನು?',
      'gps_title': 'ಹೈಪರ್ಲೋಕಲ್ GPS ಮ್ಯಾಚಿಂಗ್',
      'active_posts_count': '{count} ಸಕ್ರಿಯ ಪೋಸ್ಟ್‌ಗಳು',
      'hired_count': '{count} ನೇಮಕಗೊಂಡವರು',
      'all_jobs_cat': 'ಎಲ್ಲಾ ಕೆಲಸಗಳು',
      'cooking_cat': 'ಅಡುಗೆ',
      'delivery_cat': 'ಡೆಲಿವರಿ',
      'cleaning_cat': 'ಶುಚಿಗೊಳಿಸುವಿಕೆ',
      'shop_cat': 'ಅಂಗಡಿ',
      'labour_cat': 'ಕಾರ್ಮಿಕ',
      'repair_cat': 'ದುರಸ್ತಿ',
      'no_skills_added': 'ಯಾವುದೇ ಕೌಶಲ್ಯಗಳನ್ನು ಸೇರಿಸಲಾಗಿಲ್ಲ',
      'shop_assistant': 'ಅಂಗಡಿ ಸಹಾಯಕ',
      'delivery_partner': 'ಡೆಲಿವರಿ ಪಾಲುದಾರ',
      'immediate_start': 'ತಕ್ಷಣದ ಪ್ರಾರಂಭ',
      'no_degree': 'ಯಾವುದೇ ಪದವಿ ಅಥವಾ ಪ್ರಮಾಣಪತ್ರದ ಅಗತ್ಯವಿಲ್ಲ',
      'basic_comm': 'ಮೂಲಭೂತ ಕನ್ನಡ ಅಥವಾ ಹಿಂದಿ ಸಂವಹನ',
      'honest_punctual': 'ಪ್ರಾಮಾಣಿಕ, ಸಮಯಪ್ರಜ್ಞೆ, ಶ್ರಮಜೀವಿ',
      'lifting': 'ಬಾಕ್ಸ್‌ಗಳನ್ನು ಎತ್ತಬಲ್ಲರು (10 ಕೆಜಿ ವರೆಗೆ)',
      'free_lunch': 'ಉಚಿತ ಊಟ',
      'weekly_pay': 'ವಾರದ ವೇತನ',
      'hike': 'ವೇತನ ಹೆಚ್ಚಳ',
      'bonus': 'ಬೋನಸ್',
      'what_is_this': 'ಇದು ಏನು?',
      'community_verified': 'ಸಮುದಾಯ ಪರಿಶೀಲಿಸಲಾಗಿದೆ',
      'good': 'ಉತ್ತಮ',
      'business_name': 'ಶ್ರೀ ಗಣೇಶ್ ಪ್ರಾವಿಷನ್ ಸ್ಟೋರ್',
      'kitchen_helper': 'ಅಡುಗೆ ಸಹಾಯಕ',
      'shop_clean': 'ಅಂಗಡಿ • ಸ್ವಚ್ಛತೆ',
      'cook_shop': 'ಅಡುಗೆ • ಅಂಗಡಿ',
      'march': 'ಮಾರ್ಚ್',
      'aug': 'ಆಗಸ್ಟ್',
      'jul': 'ಜುಲೈ',
    },
    'hi': {
      'choose_language': 'अपनी भाषा चुनें',
      'choose_language_subtitle': 'अपनी पसंदीदा भाषा का चयन करें',
      'continue': 'आगे बढ़ें',
      'more_coming_soon': 'और भाषाएँ जल्द आ रही हैं',
    },
    'te': {
      'choose_language': 'మీ భాషను ఎంచుకోండి',
      'choose_language_subtitle': 'మీ ప్రాధాన్య భాషను ఎంచుకోండి',
      'continue': 'కొనసాగించండి',
      'more_coming_soon': 'మరిన్ని భాషలు త్వరలో వస్తున్నాయి',
    },
    'ml': {
      'choose_language': 'നിങ്ങളുടെ ഭാഷ തിരഞ്ഞെടുക്കുക',
      'choose_language_subtitle': 'നിങ്ങൾക്ക് താൽപ്പര്യമുള്ള ഭാഷ തിരഞ്ഞെടുക്കുക',
      'continue': 'തുടരുക',
      'more_coming_soon': 'കൂടുതൽ ഭാഷകൾ ഉടൻ വരുന്നു',
    },
    'ta': {
      'choose_language': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
      'choose_language_subtitle': 'உங்கள் விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும்',
      'continue': 'தொடரவும்',
      'more_coming_soon': 'மேலும் மொழிகள் விரைவில் வரும்',
    },
  };

  static String translate(String key, String lang, {Map<String, String>? args}) {
    String text = _translations[lang]?[key] ?? _translations['en']?[key] ?? key;
    if (args != null) {
      args.forEach((k, v) {
        text = text.replaceAll('{$k}', v);
      });
    }
    return text;
  }
}
